name: Transmission
version: ${project.version}
description: Nice and simple teleport/warp/home plugin.
author: SyntaxNode
website: http://syntaxno.de/

main: at.junction.transmission.Transmission
database: true

commands:
  msg:
    description: Send a message to another player.
    aliases: [w, whisper, tell]
    permission: transmission.msg
    usage: |
      /<command> <playername> <message>
  reply:
    description: Reply to the player who sent you the most recent message.
    aliases: r
    permission: transmission.msg
    usage: |
      /<command> <message>
  mail:
    description: Send a mail to a player.
    permission: transmission.mail
    usage: |
      /<command> <playername> <message>
  inbox:
    description: View inbox, read mail and clear messages.
    permission: transmission.mail
    usage: |
      /<command> - View inbox.
      /<command> read <#> - View message #.
      /command clear - Clear read messages.
  broadcast:
    description: Broadcast a message on behalf of the server.
    aliases: br
    permission: transmission.broadcast
    usage: |
      /<command> <message>
  staffchat:
    description: Toggle into the private staff chat.
    permission: transmission.staffchat
    aliases: [sc, mc]
    usage: |
      /<command>

permissions:
  transmission.player:
    description: Basic player access.
    default: true
    children:
      transmission.msg:
        description: Allow a player to send a message to another player.
        default: true
      transmission.mail:
        description: Allow a player to send a mail to a player.
        default: true
  transmission.broadcast:
    description: Allow a player to broadcast a message on behalf of the server.
    default: op
  transmission.staffchat:
    description: Allow a player to toggle into the private staff chat.
    default: op
