name: Transmission
version: ${project.version}
description: Nice and simple teleport/warp/home plugin.
author: SyntaxNode
website: http://syntaxno.de/

main: at.junction.transmission.Transmission
database: true

commands:
  mail:
    description: Send a mail to a player.
    permission: transmission.mail
    usage: |
      /<command> <playername> <message>
  inbox:
    description: View inbox, read mail and clear messages.
    permission: transmission.mail
    usage: |
      /<command> - View inbox.
      /<command> read <#> - View message #.
      /command clear - Clear read messages.
  staffchat:
    description: Toggle into the private staff chat.
    permission: transmission.staffchat
    aliases: [sc, mc]
    usage: |
      /<command>

permissions:
  transmission.player:
    description: Basic player access.
    default: true
    children:
      transmission.mail:
        description: Allow a player to send a mail to a player.
        default: true
  transmission.staffchat:
    description: Allow a player to toggle into the private staff chat.
    default: op
