name: Transmission
version: ${project.version}
description: Messaging plugin.
authors: [SyntaxNode, zifnab06]
website: http://github.com/junctionat/Transmission

main: at.junction.transmission.Transmission
database: true

commands:
  staffchat:
    description: Toggle into the private staff chat.
    permission: transmission.staffchat
    aliases: [sc, mc]
    usage: /<command>
  msg:
    description: Messages a player
    permission: transmission.message
    aliases: [m, w, t, tell]
    usage: /<command> <player> [message]
  reply:
    description: Replies to the last message sent
    permission: transmission.message
    aliases: [r]
    usage: /<command> [message]
  ircsay:
    description: IRC Relay command
    permission: transmission.ircsay
    usage: /ircsay [message]
  broadcast:
    description: Staff broadcast
    permission: transmission.broadcast
    aliases: [o]
    usage: /<command> [message]
  list: 
    description: List players on the server. Shows moderators seperately.
    permission: transmission.list
    usage: /<command> [message]
  mute:
    description: Mute a player. If no player name is given, shows the muted list.
    permission: transmission.mute
    usage: /<command> [<playername>]
  unmute:
    description: Unmute a player
    permission: transmission.mute
    usage: /<command> <playername>
  me:
    description: Override of bukkit's /me command - works exactly the same (except follows mute)
    permission: transmission.me
    usage: /<command> [message]
permissions:
  transmission.player:
    description: Basic player access.
    default: true
    children:
      transmission.message:
        description: Allow a player to message other players.
        default: true
      transmission.list:
        description: Allow a player to see who is on the server
        default: true
      transmission.me
        description: Allow a player to use /me
        default: true
  transmission.staff:
    description: Staff commands
    default: op
    children: 
      transmission.broadcast:
        description: Allows a player to send broadcasts
        default: op
      transmission.staffchat:
        description: Allow a player to toggle into the private staff chat.
        default: op
      transmission.mute:
        description: ALlows staff to mute players
        default: op
  transmission.ircsay:
    description: IRC Relay command
    default: op
